name: build-willow

on:
  workflow_dispatch:
    inputs:
      wake_word:
        description: 'Wake Word'
        required: true
        default: 'hey_jarvis'
        type: choice
        options:
        - hey_jarvis
        - hi_esp
        - alexa
      board:
        description: 'Board'
        required: true
        default: 'ESP32-S3-BOX'
        type: choice
        options:
        - ESP32-S3-BOX

jobs:
  build:
    runs-on: ubuntu-latest
    # PLUS DE CONTENEUR ICI (C'est ça qui bloquait)
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Willow
        # L'option --docker force le script à gérer l'image lui-même
        run: |
          chmod +x utils.sh
          ./utils.sh --docker build ${{ inputs.wake_word }} ${{ inputs.board }} --mode client

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: willow-dist
          path: dist
