name: build-willow

on:
  workflow_dispatch:
    inputs:
      wake_word:
        description: 'Wake Word'
        required: true
        default: 'hey_jarvis'
        type: choice
        options:
        - hey_jarvis
        - hi_esp
        - alexa
      board:
        description: 'Board'
        required: true
        default: 'ESP32-S3-BOX'
        type: choice
        options:
        - ESP32-S3-BOX
      mode:
        description: 'Mode'
        required: true
        default: 'client'
        type: choice
        options:
        - client

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      # ON UTILISE L'IMAGE OFFICIELLE ESPRESSIF (Toujours en ligne, pas d'erreur manifest)
      image: docker.io/espressif/idf:release-v5.1
      options: --user root

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Tools
        # On installe juste 'jq' qui manque parfois dans l'image officielle
        run: |
          apt-get update && apt-get install -y jq

      - name: Build Willow
        run: |
          git config --global --add safe.directory '*'
          . $IDF_PATH/export.sh
          # On lance le build standard
          ./utils.sh build ${{ inputs.wake_word }} ${{ inputs.board }} --mode ${{ inputs.mode }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: willow-dist
          path: dist
