name: build-willow

on:
  workflow_dispatch:
    inputs:
      wake_word:
        description: 'Wake Word'
        required: true
        default: 'hey_jarvis'
        type: choice
        options:
        - hey_jarvis
        - hi_esp
        - alexa
      board:
        description: 'Board'
        required: true
        default: 'ESP32-S3-BOX'
        type: choice
        options:
        - ESP32-S3-BOX
        - ESP32-S3-BOX-3
        - ESP32-S3-BOX-Lite
      mode:
        description: 'Mode'
        required: true
        default: 'client'
        type: choice
        options:
        - client

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/heywillow/willow-build:main
    defaults:
      run:
        working-directory: /willow

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: /willow
          submodules: recursive

      - name: Build Willow
        run: |
          ./utils.sh build ${{ inputs.wake_word }} ${{ inputs.board }} --mode ${{ inputs.mode }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: willow-dist
          path: /willow/dist
