name: build-willow

on:
  workflow_dispatch:
    inputs:
      wake_word:
        description: 'Wake Word'
        required: true
        default: 'hi_esp'
        type: choice
        options:
        - hi_esp
        - alexa
        - hey_jarvis

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build with Tovera Image
        uses: addnab/docker-run-action@v3
        with:
          # On utilise l'image maintenue par Tovera qui possède TOUS les fichiers board.h
          image: ghcr.io/toverainc/willow-build:latest
          options: -v ${{ github.workspace }}:/willow
          run: |
            cd /willow
            # Cette image contient déjà l'environnement exporté et les dépendances
            ./utils.sh build ${{ inputs.wake_word }} ESP32-S3-BOX --mode client

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: willow-dist
          path: dist
