name: build-willow

on:
  workflow_dispatch:
    inputs:
      wake_word:
        description: 'Wake Word'
        required: true
        default: 'hey_jarvis'
        type: choice
        options:
        - hey_jarvis
        - hi_esp
        - alexa
      board:
        description: 'Board'
        required: true
        default: 'ESP32-S3-BOX'
        type: choice
        options:
        - ESP32-S3-BOX

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/heywillow/willow-build:main
      options: --user root

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Willow
        run: ./utils.sh build ${{ inputs.wake_word }} ${{ inputs.board }} --mode client

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: willow-dist
          path: dist
