name: build-willow

on:
  workflow_dispatch:
    inputs:
      wake_word:
        description: 'Wake Word'
        required: true
        default: 'hey_jarvis'
        type: choice
        options:
        - hey_jarvis
        - hi_esp
        - alexa
      board:
        description: 'Board'
        required: true
        default: 'ESP32-S3-BOX'
        type: choice
        options:
        - ESP32-S3-BOX
      mode:
        description: 'Mode'
        required: true
        default: 'client'
        type: choice
        options:
        - client

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      # On garde l'image officielle Espressif car elle est stable
      image: docker.io/espressif/idf:release-v5.1
      options: --user root

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive # On laisse GitHub gérer les sous-dossiers proprement

      - name: Install Tools
        run: |
          apt-get update && apt-get install -y jq git curl wget

      - name: Build Willow
        shell: bash
        run: |
          # 1. Sécurité Git
          git config --global --add safe.directory '*'
          
          # 2. On charge les outils ESP
          . $IDF_PATH/export.sh
          
          # 3. LE PATCH : On désactive la commande git qui plante dans le script
          # On remplace "git submodule update..." par un commentaire "# skipped"
          sed -i 's/git submodule update --init --recursive/# skipped crashing git command/g' utils.sh
          
          # 4. On lance l'installation (qui ne plantera plus grâce au patch)
          ./utils.sh install
          
          # 5. On lance la fabrication
          ./utils.sh build ${{ inputs.wake_word }} ${{ inputs.board }} --mode ${{ inputs.mode }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: willow-dist
          path: dist
